version: '3.6'

services:
  scraper_test:
    build: .
    environment:
      DEBUG: ${DEBUG}
      SQL_SERVER: ${SQL_SERVER}
      SQL_USERNAME: ${SQL_USERNAME}
      SQL_PASSWORD: ${SQL_PASSWORD}
    command: pytest test_scraper.py

networks:
  default:
    external: true
    name: scraper_network