version: '3.6'

services:
  mysqldb:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: master
      MYSQL_USER: ${SQL_USERNAME}
      MYSQL_PASSWORD:  ${SQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

networks:
  default:
    external: true
    name: scraper_network